# ARENAS
# [x, y, z]
# EXAMPLE: [168, -3, 69]
ARENA1-WORLD: ''
ARENA1: []
# -----------------------
ARENA2-WORLD: ''
ARENA2: []
# -----------------------
ARENA3-WORLD: ''
ARENA3: []
# -----------------------
ARENA4-WORLD: ''
ARENA4: []
# -----------------------
ARENA5-WORLD: ''
ARENA5: []
# -----------------------
ARENA6-WORLD: ''
ARENA6: []
# -----------------------
ARENA7-WORLD: ''
ARENA7: []
# -----------------------
ARENA8-WORLD: ''
ARENA8: []
# -----------------------
ARENA9-WORLD: ''
ARENA9: []
# -----------------------
ARENA10-WORLD: ''
ARENA10: []
# -----------------------
ARENA11-WORLD: ''
ARENA11: []
# -----------------------
ARENA12-WORLD: ''
ARENA12: []
# -----------------------
ARENA13-WORLD: ''
ARENA13: []
# -----------------------
ARENA14-WORLD: ''
ARENA14: []
# -----------------------
ARENA15-WORLD: ''
ARENA15: []
# -----------------------
ARENA16-WORLD: ''
ARENA16: []
# -----------------------
ARENA17-WORLD: ''
ARENA17: []
# -----------------------
ARENA18-WORLD: ''
ARENA18: []
# -----------------------
ARENA19-WORLD: ''
ARENA19: []
# -----------------------
ARENA20-WORLD: ''
ARENA20: []
# -----------------------
ARENA21-WORLD: ''
ARENA21: []
# -----------------------
ARENA22-WORLD: ''
ARENA22: []
# -----------------------
ARENA23-WORLD: ''
ARENA23: []
# -----------------------
ARENA24-WORLD: ''
ARENA24: []
# -----------------------
ARENA25-WORLD: ''
ARENA25: []
# -----------------------
ARENA26-WORLD: ''
ARENA26: []
# -----------------------
ARENA27-WORLD: ''
ARENA27: []
# -----------------------
ARENA28-WORLD: ''
ARENA28: []
# -----------------------
ARENA29-WORLD: ''
ARENA29: []
# -----------------------
ARENA30-WORLD: ''
ARENA30: []